wandb_version: 1

architecture:
  desc: null
  value: NLST_CNN
dataset_id:
  desc: null
  value: NLST
data_split:
  desc: null
  value: no_split
optimizer:
  desc: null
  value: Adam
FL Algorithm:
  desc: null
  value: FedAvg
Privacy:
  desc: null
  value: None
job_id:
  desc: null
  value: '1722963617'
client:
  desc: null
  value: site-2
run_name:
  desc: null
  value: exp1_1_NS_FL
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1722963618
    t:
      1:
      - 1
      - 41
      - 53
      - 55
      3:
      - 13
      - 15
      - 16
      - 23
      4: 3.10.12
      5: 0.17.3
      8:
      - 5
      - 9
      13: linux-x86_64
